### ISSUE TITLE
extconf.rb failed - Could not create Makefile due to some reason

### ISSUE THREAD

**Issue by dshevtsov** [davidfstr/rdiscount#134]
rdiscount installation fails.

Environment:
- Windows 7 Enterprise x64
- Ruby 2.0.0-p647 (x64)
- DevKit-mingw64-64-4.7.2-20130224-1432-sfx

```
C:\Ruby200-x64\lib\ruby\gems\2.0.0\gems\rdiscount-2.1.8\ext>ruby -rdevkit extconf.rb
Temporarily enhancing PATH to include DevKit...
checking for random()... no
checking for srandom()... no
checking for rand()... yes
checking for srand()... yes
checking size of unsigned long... 4
checking size of unsigned int... failed
checking size of unsigned short... 2
no int with size 2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby200-x64/bin/ruby
        --with-rdiscount-dir
        --without-rdiscount-dir
        --with-rdiscount-include
        --without-rdiscount-include=${rdiscount-dir}/include
        --with-rdiscount-lib
        --without-rdiscount-lib=${rdiscount-dir}/
```

**Comment by segiddins** [comment]
What version of RubyGems are you running?

**Comment by dshevtsov** [comment]
2.0.14.1

**Comment by theimowski** [comment]
any update on this? I'm having the same problem 

windows 7 pro x64
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]
DevKit-mingw64-32-4.7.2-20130224-1151-sfx
gem --version 2.4.5.1

**Comment by davidfstr** [comment]
Soon this won't apply because RDiscount 2.2.0 will be out. Plan to retest on Windows prior to release.

**Comment by davidfstr** [comment]
RDiscount 2.2.0.1 has been released. Let me know if you're still having the same problem.

**Comment by shjustinzhang** [comment]
Win10 x64
ruby 2.2.6p396 (2016-11-15 revision 56800) [x64-mingw32]
DevKit-mingw64-32-4.7.2-20130224-1151-sfx
gem -V 2.4.5.2

I have this problem as well, any suggestion ?

C:\DevKit>gem install rdiscount --platform=ruby
Building native extensions.  This could take a while...
ERROR:  Error installing rdiscount:
        ERROR: Failed to build gem native extension.

    C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20220628-28272-nsvcg2.rb extconf.rb
checking for random()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby22-x64/bin/$(RUBY_BASE_NAME)
        --with-rdiscount-dir
        --without-rdiscount-dir
        --with-rdiscount-include
        --without-rdiscount-include=${rdiscount-dir}/include
        --with-rdiscount-lib
        --without-rdiscount-lib=${rdiscount-dir}/lib
C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:1020:in `block in have_func'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from C:/Ruby22-x64/lib/ruby/2.2.0/mkmf.rb:1019:in `have_func'
        from extconf.rb:5:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rdiscount-2.2.0.2 for inspection.
Results logged to C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/rdiscount-2.2.0.2/gem_make.out

**Comment by shjustinzhang** [comment]
Issue get solved, the point is to match corresponding DevKit and Citification about SSL.
