### ISSUE TITLE
Links with right parenthesis rendering

### ISSUE THREAD

**Issue by fliiiix** [davidfstr/rdiscount#151]
Notably Wikipedia is using `)` in urls, which breaks with rdiscount see example:

```
require "rdiscount"

markdown = RDiscount.new("[wikipedia](https://en.wikipedia.org/wiki/Peter_Eckersley_(computer_scientist))")
puts markdown.to_html
```

will produce:
```
<p><a href="https://en.wikipedia.org/wiki/Peter_Eckersley_(computer_scientist">wikipedia</a>)</p>
```

Which is a broken link.

Is that intended?

**Comment by davidfstr** [comment]
> Is that intended?

Try checking the behavior of upstream Discount: http://www.pell.portland.or.us/~orc/Code/discount/

I'm guessing this behavior _is_ intended, because it's not straightforward to distinguish a close paren in a URL from a close paren that stops a link. So I'm tentatively resolving as expected behavior.

**Comment by fliiiix** [comment]
Just confirmed 

```
$ markdown foo.bar 
<p><a href="https://en.wikipedia.org/wiki/Peter_Eckersley_(computer_scientist">wikipedia</a>)</p>
$ cat foo.bar 
[wikipedia](https://en.wikipedia.org/wiki/Peter_Eckersley_(computer_scientist))
```

i will report that in the upstream lib

**Comment by fliiiix** [comment]
upstream issue for ref: https://github.com/Orc/discount/issues/260
