### ISSUE TITLE
HTML5 elements

### ISSUE THREAD

**Issue by wailqill** [davidfstr/rdiscount#21]
Hi,

I saw that you've pulled in a patch from rcrowley (a603534d6dc9b2a77d376be1f11fe2f62d9bc641), and begun the support for HTML5 elements. It's not used in the final code though, and I wonder why? Or rather, how can I enable it?

.glenn

**Comment by digitalvapor** [comment]
@davidfstr html5 elements such as `section` or like @imathis says, `figure` are being wrapped differently than the standard elements such as `div`.

example:
```
<section>

test

</section>
```

inserted in a markdown file would render as

```
<p><section></p>

<p>test</p>

<p></section></p>
```

**Comment by davidfstr** [comment]
@digitalvapor: This issue is 5 years old and was closed 2 years ago due to it not providing a specific request.

Please open a new issue and clearly describe what you seek.

**Comment by digitalvapor** [comment]
you could re-open if you wish, it is described rather well already. fix can be seen in @mnarayan01's branch https://github.com/mnarayan01/rdiscount/commit/23434d7746cc1d9b467260011fb199c648b39a41

**Comment by davidfstr** [comment]
> html5 elements such as `section` or like @imathis says, `figure` are being wrapped differently than the standard elements such as `div`.

Okay I think I understand this issue a bit better. There are some HTML5-specific tags are not being interpreted in the expected fashion.

Since this issue lies in the underlying Discount parser (and not RDiscount's wrapper thereof), you'd need to bring this issue to the attention of Discount at: https://github.com/Orc/discount . I'd suggest filing an issue there.

Once a fix is released in Discount, it can be pulled into RDiscount.
